### ISSUE TITLE
Seedlots and Trial Descent

### ISSUE THREAD

**Issue by dauglyon** [plantbreeding/BrAPI#236]
BrAPI suggestion/want/need:
Some sort of relationship (or path of relationships) in BrAPI that can define the transfer of germplasm between trials. I put a little ASCII graph in this issue on SGN: https://github.com/solgenomics/sgn/issues/1817 describing how that might look. Seedlots seem like the best option as they also enable a bunch of other things in the realm of inventory management.

**Comment by bauchetg** [comment]
This would improve experimental tracking for:
-1- Trial experiment chronology and staging (ie: PYT, AYT, UYT.)
-2- Get user based information on trial sources (ie for Multiple years &  Multi-Environment analysis)
-3- Have a related visualization interface (ie: flow chart)

**Comment by BrapiCoordinatorSelby** [comment]
`seedLot` concept has been added to BrAPI V2.0, I'm not sure if it completely addresses this issue...

**Comment by dauglyon** [comment]
@BrapiCoordinatorSelby Looking at [seedLot.yaml](https://github.com/plantbreeding/API/blob/brapi-v2-dev/Specification/BrAPI-Germplasm/SeedLots/Schemas/seedLot.yaml), I think what would be needed is a `SourceCross` concept or the like (IDK how v2.0 plans on handling crosses), basically so one can take a seedlot and see where it was generated. Observation units would also need a concept of `SourceSeedlot` in order to make this work, allowing someone to look at any crossing trial and track the source of the genetic material therein back to previously performed trials (recursively). In a perfect world, this could replace germplasm pedigree information (because the contents of a seedlot being the result of a cross implies germplasm contained in that seedlot to have the cross as parents) but, from what I understand, that's a just a dream mostly due to the lack of seedlot-level decent information.

**Comment by BrapiCoordinatorSelby** [comment]
As of V2.1, I believe this issue is complete. As described by @dauglyon, SeedLots have a link to Crosses, and ObservationUnits have a link to SeedLots. The `Source...` parts of the suggested field names were not included, but otherwise the functionality should be available. Please re-open this issue if I am wrong.
