### ISSUE TITLE
Bulk *-search like calls for progeny and pedigree.

### ISSUE THREAD

**Issue by dauglyon** [plantbreeding/BrAPI#239]
When expanding/exploring pedigree trees it quickly becomes cumbersome to make an individual call for each of the many accessions one might be seeking the children for. Thus, I propose a new call for that purpose.

## Caveat

The current URL structure `brapi/v1/germplasm/$germplasmDbId/progeny` is not easily converted to a search like structure. So adding a `brapi/v1/progeny/$germplasmDbId` object might be needed, however this isnt quite idiomatcly RESTful as $germplasmDbId is not an ID for the progeny object itself, but makes the most sense to use IMO.

**Comment by patrick-koenig** [comment]
Wouldn't this be more REST-idiomatic?

`/brapi/v1/progeny-search?gerplasmDbId=12345`

**Comment by dauglyon** [comment]
@patrick-koenig Yes! Much better, thanks!

**Comment by dauglyon** [comment]
@BrapiCoordinatorSelby has this been triaged?

**Comment by BrapiCoordinatorSelby** [comment]
@dauglyon not any further since you and I talked about it IRL.

**Comment by BrapiCoordinatorSelby** [comment]
Idea for this. Would a `depth` query parameter solve your needs. Default value of 1 to maintain the current behavior, but if `depth` > 1, additional levels of the tree would be returned. 

Example
`/germplasm/{germplasmDbId}/pedigree?depth=3`
would return all parents, grandparents, and great grandparents.
Similarly
`/germplasm/{germplasmDbId}/progeny?depth=3`
would return all children, grandchildren, and great grandchildren.

**Comment by dauglyon** [comment]
In terms of pre-loading a pedigree tree (and resolving inbred relationships), the tricky bit comes when one wants to load all the Ancestors `A(N)` of node `N` and all the children for each of those ancestors  `C(a) for a in A(N)`. Your suggestions covers the first half, but not the second. Though I think it would be good to include regardless.
