### ISSUE TITLE
Default page size for Genotype Calls API from 1000 to 1 Million

### ISSUE THREAD

**Issue by vg249** [plantbreeding/BrAPI#442]
Brapi default page size for brapi genotype calls is 1000 for now.

Genotypes are stored usually as matrices. For example, a small dataset with 5000 marker with 1000 samples will have 5 million data points ends up making 5000 requests to server.

It is not an issue when BrAPI data sources are deployed in local servers. With servers deployed in AWS, It creates lot of read I/Os which becomes a problem when I/O cap limits reach fast. (Imagine, If some application sets pageSize as 10 or 1 against a large dataset). We are adding the restriction of minimum page size to the genotype calls.
So, Assuming everyone will face similar problems, as genotype data are usually large, I propose to change default page size from 1000 to 1000000(1000*1000 matrix) just for Genotype Calls, as an effective way to communicate to the developers who develop applications against BrAPI server. Any other way to communicate about the page size restrictions directly through brapi specification is also welcome.

**Comment by BrapiCoordinatorSelby** [comment]
@vg249 with the addition of #451 and the work being done by the Genotyping working group, is this change still helpful or necessary?

**Comment by BrapiCoordinatorSelby** [comment]
This issue is now unnecessary due to the work in #451
