### ISSUE TITLE
different terms data and items meaning the same

### ISSUE THREAD

**Issue by mverouden** [plantbreeding/BrAPI#444]
In POST /lists the data argument reflects the list of DbIds contained in this list. Whereas in POST /lists/{listDbId}/items the same information is called items.

The description of the POST /lists/{listDbId}/items states: Add items to a specific list, and the explanation say: Add new data to a specific generic list. This is at least a bit weird in my opinion.

In a new version of the specs I would propose in order to make it more consistent to use the term items in both cases. Therefore call the argument items instead of data in POST /lists and in the explanation of the POST /lists/{listDbId}/items call use: "Add new items to a specific generic list".

**Comment by BrapiCoordinatorSelby** [comment]
There is a small complication with this. 
There is a general BrAPI rule which says pagination only applies to the `data` array, and the `data` array is used in `GET /lists/{listDbId}` so very long lists can be paginated. `POST /lists` aligns with the GET object structure and uses the `data` field even though there is no pagination during the POST. 
So maybe `POST /lists/{listDbId}/items` should be become `POST /lists/{listDbId}/data` so it also aligns with the other two?

**Comment by mverouden** [comment]
That would make sense given the nature of pagination and would still make it more consistent.
