### ISSUE TITLE
searching ReferenceSets

### ISSUE THREAD

**Issue by GuilhemSempere** [plantbreeding/BrAPI#473]
ReferenceSet seems a bit disconnected from the "non-genotyping" part of the model. I mean it's no problem going down from ReferenceSet to Reference and then to Variant, however searching for ReferenceSets can be achieved either by :
- explicitly passing their IDs,but where do we get them from?
- specifying assemblyPUIs, a field that exists nowhere else in the model
- specifying accessions: I'm not clear with what kind of accession is expected here, I found "NC_000001.11" as example data, which to me is an NCBI sequence (= BrAPI reference, not ReferenceSet)
Thus I'd like to know what you guys think about being able to search ReferenceSets by studyDbIds. I have the feeling that it would make sense to be able to specify a genotyping-study id and expect to have in return the list of sequences that are involved in it.

**Comment by BrapiCoordinatorSelby** [comment]
I have added the ability to search References and RefernceSets by the Program/Trial/Study set of parameters. I also added Germplasm as a parameter and part of the response model, in an effort to supplement the "sourceAccessions" concept that is there from the original GA4GH model. I hope this achieves the goal of connecting references in with the rest of the BrAPI spec.
