### ISSUE TITLE
How to post pedigree trees?

### ISSUE THREAD

**Issue by mcrimi** [plantbreeding/BrAPI#481]
Hi @BrapiCoordinatorSelby,

Maybe this has been raised before (did quick search and couldn't find any relevant topic) but I'm wondering how would BrAPI v2 enable moving pedigrees from one place to the other.

The use case is the following: In **System 1** I have germplasm C which is the progeny of A and B and I want to move this tree to **System 2**. I can create A, B and C in **System 2**, but I don't find a way to connect them. Am I missing something? Maybe we need a `PUT /germplasm/{germplasmDbId}/pedigree` call which takes C as a parameter where I can define A and B as `"parents": []`? Another idea would be to extend the `PUT/germplasm/{germplasmDbId} `with the parents.

Thoughts?

Thanks!

cc: @nahuel-soldevilla

**Comment by BrapiCoordinatorSelby** [comment]
The only way to POST/PUT pedigree information right now is by parsing the pedigree string. The Germplasm entity has a string field `pedigree` which can be used to send the parental information. This method is not ideal as it relies on string parsing and there is a loss of information compared to the full Pedigree object, but it is a work around that will work in v2.0

I will add this issue to v2.1 to take a look. @timparsons was asking about this same problem

**Comment by jcdpineda** [comment]
Hi @BrapiCoordinatorSelby 

Was wondering if this enhancement also covers the use case below:

If we do a POST /germplasm in v2.1 with the following data:

```
[
  {
    "germplasmName": "Tomato",
    "pedigree": "parent1/parent2"
    ...
  }
]
```

Will v2.1 have a `GET /germplasm/germplasmDbId/pedigree` endpoint? If yes, will there be a way to extract parent information individually? Similar to the json below:

```
[
  {
    "germplasmDbId": "001",
    "germplasmName": "Tomato",
    "pedigree": "parent1/parent2"
    "parent1_id": "1001"
    "parent2_id": "1002"
  }
]
```

**Comment by BrapiCoordinatorSelby** [comment]
yes, that issue will cover several use cases regarding pedigree. There will be a way to POST full pedigree trees with all of the relevant information. In v2.1 you shouldn't need to rely on the `pedigree` string value to assign parents.
It will be something like `POST /pedigree` and/or `POST /germplasm/germplasmDbId/pedigree` to send full pedigree objects to the server. 
When I have something designed I will share it with everyone on this issue for review

**Comment by jcdpineda** [comment]
@BrapiCoordinatorSelby  it would be nice if we can filter germplasm records according to `commonCropNames`, `familyCode`, `instituteCode`, using using the POST /search/germplasm endpoint:

```
[
    "commonCropNames": ["Tomato"],
    "familyCode": ["001", "002", "003"]
    "instituteCode": ["BRP"],
]
```

**Comment by BrapiCoordinatorSelby** [comment]
@mcrimi @jcdpineda @nahuel-soldevilla @timparsons @MFlores2021 
Please review the new Pedigree endpoints that have been developed in the V2.1 developer preview
Apiary: https://brapigermplasm21.docs.apiary.io/#/reference/pedigree?mc=reference%2Fpedigree%2Fget-pedigree%2Fget-pedigree%2F200
SwaggerHub: https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI-Germplasm/2.1#/Pedigree/get_pedigree

**Comment by jcdpineda** [comment]
@BrapiCoordinatorSelby 

I have no objections with the updates. Thank you for including `instituteCodes` in the `POST /search/germplasm` endpoint. Looking forward to the updated docker image of the test server.

Thank you very much!
